//
// Created by 杨乐 on 2018/12/10.
//

#ifndef YOURSQL_SM_PUBLIC_H
#define YOURSQL_SM_PUBLIC_H


#include "SM_Manager.h"
#include "../yoursql.h"
const RC SM_INVALID_DB_NAME = 1;
const RC SM_NAME_TOO_LONG = SM_INVALID_DB_NAME + 1;
const RC SM_SAME_NAME_ATTR = SM_NAME_TOO_LONG + 1;
const RC SM_NONEXIST_RELATION = SM_SAME_NAME_ATTR + 1;
const RC SM_NONEXIT_ATTR = SM_NONEXIST_RELATION + 1;
const RC SM_DB_NOT_CLOSE = SM_NONEXIT_ATTR + 1;
const RC SM_ILLEGAL_NAME = SM_DB_NOT_CLOSE + 1;
const RC SM_TABLE_EXIST = SM_ILLEGAL_NAME + 1;
const RC SM_CLOSE = SM_TABLE_EXIST + 1;

const RC SM_SYSCALL_ERROR = -1;

#endif //YOURSQL_SM_PUBLIC_H
