//
// Created by 杨乐 on 2019/1/5.
//

#ifndef YOURSQL_PARSERERROR_H
#define YOURSQL_PARSERERROR_H

#include "../errorhandle.h"

const int PASERR_MULTIPLE_PRIMARY = YOURSQL_PARSER_ERROR_START;
const int PASERR_PRIMARY_NOTFOUND = PASERR_MULTIPLE_PRIMARY + 1;
const int PASERR_ATTR_TOOLONG = PASERR_PRIMARY_NOTFOUND + 1;
const int PASERR_FOREIGN_NOTFOUND = PASERR_ATTR_TOOLONG + 1;
const int PASERR_FOREIGN_MULTIPLE = PASERR_FOREIGN_NOTFOUND + 1;

#endif //YOURSQL_PARSERERROR_H
