//
// Created by eric on 18-11-26.
//

#ifndef YOURSQL_IX_PUBLIC_H
#define YOURSQL_IX_PUBLIC_H
const RC IX_LEAF_SPLIT_UNIMPLETATED = 1;

const RC IX_INVALID_INDEXNO = -1;
const RC IX_RID_OF_SAME_ATTR_EXCEED = IX_INVALID_INDEXNO - 1;
#endif //YOURSQL_IX_PUBLIC_H
