//
// Created by eric on 18-11-26.
//

#ifndef YOURSQL_IX_PUBLIC_H
#define YOURSQL_IX_PUBLIC_H
const RC IX_ITERATOR_TO_END = 1;
const RC IX_EMPTY_TREE = IX_ITERATOR_TO_END + 1;

const RC IX_INVALID_INDEXNO = -1;
const RC IX_RID_OF_SAME_ATTR_EXCEED = IX_INVALID_INDEXNO - 1;
const RC IX_NO_INDEX_EXIST=IX_RID_OF_SAME_ATTR_EXCEED-1;
const RC IX_INDEX_OPENED=IX_NO_INDEX_EXIST-1;
const RC IX_INDEX_NOT_OPENED=IX_INDEX_OPENED-1;
const RC IX_UNLIMITED_DUPLICATE_KEY = IX_INDEX_NOT_OPENED-1;
#endif //YOURSQL_IX_PUBLIC_H
