//
// Created by eric on 18-11-26.
//

#ifndef YOURSQL_IX_PUBLIC_H
#define YOURSQL_IX_PUBLIC_H

#include "../errorhandle.h"

const int IX_ITERATOR_TO_END = YOURSQL_IX_ERROR_START;
const int IX_EMPTY_TREE = IX_ITERATOR_TO_END + 1;

const int IX_INVALID_INDEXNO = -1;
const int IX_RID_OF_SAME_ATTR_EXCEED = IX_INVALID_INDEXNO - 1;
const int IX_NO_INDEX_EXIST=IX_RID_OF_SAME_ATTR_EXCEED-1;
const int IX_INDEX_OPENED=IX_NO_INDEX_EXIST-1;
const int IX_INDEX_NOT_OPENED=IX_INDEX_OPENED-1;
const int IX_UNLIMITED_DUPLICATE_KEY = IX_INDEX_NOT_OPENED-1;

#endif //YOURSQL_IX_PUBLIC_H
